### ISSUE TITLE
Cant get it work for private Data

### ISSUE THREAD

**Issue by thepok** [trenki2/KrakenApi#1]
Hello, public API works fine, but when i use private part i get EAPI:Signature Error back. Any idea?

**Comment by trenki2** [comment]
Requesting private data like for instance the account balance using the GetAccountBalance() method works fine for me. Maybe you don't have setup the correct privileges for your API-Key on the Kraken site.

**Comment by thepok** [comment]
Thank you, something was wron with my keys, well who knows, with a new generated one it worked :) thank you for your fast Help!
